name: 'Main'
on: [push]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: 'Install'
        run: pnpm install
      - name: 'Build'
        run: pnpm -r build

